packages:
  - cantrip_app
  - cantrip_site
  - cantrip_server
  - cantrip_worker
  - packages/*

allowBuilds:
  esbuild: true
  node-pty: true
  sharp: true

engineStrict: true
injectWorkspacePackages: true
patchedDependencies:
  webdav-server@2.6.3: patches/webdav-server@2.6.3.patch
saveWorkspaceProtocol: rolling
sharedWorkspaceLockfile: true
