UPDATE "chat_import_jobs" SET "progress" = "progress" - 'message' WHERE "progress" ? 'message';--> statement-breakpoint
UPDATE "chat_relocation_jobs" SET "progress" = "progress" - 'message' WHERE "progress" ? 'message';--> statement-breakpoint
UPDATE "project_replica_jobs" SET "progress" = "progress" - 'message' WHERE "progress" ? 'message';--> statement-breakpoint
UPDATE "projects" SET "setup_error" = NULL WHERE "setup_error" IS NOT NULL AND "setup_error" !~ '^(?:[a-z]+(?:-[a-z]+)*|ctrr_[A-Za-z0-9_-]{43})$';--> statement-breakpoint
ALTER TABLE "chat_import_jobs" DROP CONSTRAINT "chat_import_jobs_error_shape_check";--> statement-breakpoint
ALTER TABLE "chat_relocation_jobs" DROP CONSTRAINT "chat_relocation_jobs_error_shape_check";--> statement-breakpoint
ALTER TABLE "project_folder_setup_jobs" DROP CONSTRAINT "project_folder_setup_jobs_error_shape_check";--> statement-breakpoint
ALTER TABLE "project_github_conversion_jobs" DROP CONSTRAINT "project_github_conversion_jobs_error_shape_check";--> statement-breakpoint
ALTER TABLE "project_replica_jobs" DROP CONSTRAINT "project_replica_jobs_error_shape_check";--> statement-breakpoint
ALTER TABLE "chat_import_jobs" DROP COLUMN "last_error_message";--> statement-breakpoint
ALTER TABLE "chat_relocation_jobs" DROP COLUMN "last_error_message";--> statement-breakpoint
ALTER TABLE "project_folder_setup_jobs" DROP COLUMN "last_error_message";--> statement-breakpoint
ALTER TABLE "project_github_conversion_jobs" DROP COLUMN "last_error_message";--> statement-breakpoint
ALTER TABLE "project_replica_jobs" DROP COLUMN "last_error_message";--> statement-breakpoint
ALTER TABLE "chat_import_jobs" ADD CONSTRAINT "chat_import_jobs_progress_minimized_check" CHECK (jsonb_typeof("chat_import_jobs"."progress") = 'object' AND "chat_import_jobs"."progress" - 'stage' - 'percent' - 'updatedAt' = '{}'::jsonb AND ("chat_import_jobs"."progress"->>'stage') IN ('queued', 'reading', 'importing', 'awaiting-hydration', 'hydrating', 'blocked', 'failed', 'succeeded'));--> statement-breakpoint
ALTER TABLE "chat_import_jobs" ADD CONSTRAINT "chat_import_jobs_error_shape_check" CHECK (("chat_import_jobs"."last_error_code" IS NULL AND "chat_import_jobs"."error_retryable" IS NULL) OR ("chat_import_jobs"."last_error_code" IS NOT NULL AND "chat_import_jobs"."error_retryable" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "chat_relocation_jobs" ADD CONSTRAINT "chat_relocation_jobs_progress_minimized_check" CHECK (jsonb_typeof("chat_relocation_jobs"."progress") = 'object' AND "chat_relocation_jobs"."progress" - 'stage' - 'percent' - 'updatedAt' = '{}'::jsonb AND ("chat_relocation_jobs"."progress"->>'stage') IN ('queued', 'waiting-for-idle', 'recovering', 'validating', 'preparing-replica', 'transferring-attachments', 'hydrating-runtime', 'ready-to-commit', 'blocked', 'failed', 'succeeded', 'cancelled'));--> statement-breakpoint
ALTER TABLE "chat_relocation_jobs" ADD CONSTRAINT "chat_relocation_jobs_error_shape_check" CHECK (("chat_relocation_jobs"."last_error_code" IS NULL AND "chat_relocation_jobs"."error_retryable" IS NULL) OR ("chat_relocation_jobs"."last_error_code" IS NOT NULL AND "chat_relocation_jobs"."error_retryable" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "project_folder_setup_jobs" ADD CONSTRAINT "project_folder_setup_jobs_error_shape_check" CHECK (("project_folder_setup_jobs"."last_error_code" IS NULL AND "project_folder_setup_jobs"."error_retryable" IS NULL) OR ("project_folder_setup_jobs"."last_error_code" IS NOT NULL AND "project_folder_setup_jobs"."error_retryable" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "project_github_conversion_jobs" ADD CONSTRAINT "project_github_conversion_jobs_error_shape_check" CHECK (("project_github_conversion_jobs"."last_error_code" IS NULL AND "project_github_conversion_jobs"."error_retryable" IS NULL) OR ("project_github_conversion_jobs"."last_error_code" IS NOT NULL AND "project_github_conversion_jobs"."error_retryable" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "project_replica_jobs" ADD CONSTRAINT "project_replica_jobs_progress_minimized_check" CHECK (jsonb_typeof("project_replica_jobs"."progress") = 'object' AND "project_replica_jobs"."progress" - 'stage' - 'percent' - 'updatedAt' = '{}'::jsonb AND ("project_replica_jobs"."progress"->>'stage') IN ('queued', 'dispatching', 'validating', 'validating-placement', 'inspecting-existing-checkout', 'fetching', 'inspecting', 'materializing', 'resolving-revision', 'verifying', 'fast-forwarding', 'removing', 'blocked', 'failed', 'succeeded', 'cancelled'));--> statement-breakpoint
ALTER TABLE "project_replica_jobs" ADD CONSTRAINT "project_replica_jobs_error_shape_check" CHECK (("project_replica_jobs"."last_error_code" IS NULL AND "project_replica_jobs"."error_retryable" IS NULL) OR ("project_replica_jobs"."last_error_code" IS NOT NULL AND "project_replica_jobs"."error_retryable" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_setup_error_minimized_check" CHECK ("projects"."setup_error" IS NULL OR "projects"."setup_error" ~ '^(?:[a-z]+(?:-[a-z]+)*|ctrr_[A-Za-z0-9_-]{43})$');
