ALTER TABLE "workspace_repository_candidates" DROP CONSTRAINT "workspace_repository_candidates_import_state_check";--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD COLUMN "import_project_id" text;--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD COLUMN "protected_import_name" jsonb;--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD COLUMN "import_repository_blind_index" text;--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD COLUMN "import_attempt" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD COLUMN "import_command_id" text;--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD COLUMN "import_error_code" text;--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD COLUMN "import_error_retryable" boolean;--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD COLUMN "import_available_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD COLUMN "import_lease_expires_at" timestamp with time zone;--> statement-breakpoint
CREATE UNIQUE INDEX "workspace_repository_candidates_import_command_unique" ON "workspace_repository_candidates" USING btree ("import_command_id") WHERE "workspace_repository_candidates"."import_command_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "workspace_repository_candidates_import_dispatch_index" ON "workspace_repository_candidates" USING btree ("import_state","import_available_at","created_at");--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD CONSTRAINT "workspace_repository_candidates_import_execution_shape_check" CHECK (("workspace_repository_candidates"."import_state" = 'importing' AND "workspace_repository_candidates"."import_command_id" IS NOT NULL AND "workspace_repository_candidates"."import_lease_expires_at" IS NOT NULL) OR ("workspace_repository_candidates"."import_state" <> 'importing' AND "workspace_repository_candidates"."import_command_id" IS NULL AND "workspace_repository_candidates"."import_lease_expires_at" IS NULL));--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD CONSTRAINT "workspace_repository_candidates_import_error_shape_check" CHECK (("workspace_repository_candidates"."import_state" IN ('blocked', 'failed') AND "workspace_repository_candidates"."import_error_code" IS NOT NULL AND "workspace_repository_candidates"."import_error_retryable" IS NOT NULL) OR ("workspace_repository_candidates"."import_state" NOT IN ('blocked', 'failed') AND "workspace_repository_candidates"."import_error_code" IS NULL AND "workspace_repository_candidates"."import_error_retryable" IS NULL));--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD CONSTRAINT "workspace_repository_candidates_import_error_code_check" CHECK ("workspace_repository_candidates"."import_error_code" IS NULL OR "workspace_repository_candidates"."import_error_code" IN ('worker-offline', 'capability-missing', 'repository-unavailable', 'repository-changed', 'project-conflict', 'import-failed'));--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD CONSTRAINT "workspace_repository_candidates_import_payload_shape_check" CHECK ("workspace_repository_candidates"."import_state" = 'pending' OR ("workspace_repository_candidates"."import_project_id" IS NOT NULL AND "workspace_repository_candidates"."protected_import_name" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD CONSTRAINT "workspace_repository_candidates_import_attempt_check" CHECK ("workspace_repository_candidates"."import_attempt" >= 0);--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD CONSTRAINT "workspace_repository_candidates_import_availability_check" CHECK (("workspace_repository_candidates"."import_state" IN ('queued', 'importing') AND "workspace_repository_candidates"."import_available_at" IS NOT NULL) OR ("workspace_repository_candidates"."import_state" NOT IN ('queued', 'importing') AND "workspace_repository_candidates"."import_available_at" IS NULL));--> statement-breakpoint
ALTER TABLE "workspace_repository_candidates" ADD CONSTRAINT "workspace_repository_candidates_import_state_check" CHECK ("workspace_repository_candidates"."import_state" IN ('pending', 'queued', 'importing', 'imported', 'blocked', 'failed', 'skipped'));