name: cantrip-app
region: nyc

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

domains:
  - domain: cantrip.art
    type: PRIMARY
  - domain: app.cantrip.art
    type: ALIAS

features:
  - buildpack-stack=ubuntu-22

ingress:
  rules:
    - component:
        name: site
      match:
        authority:
          exact: cantrip.art
        path:
          prefix: /
    - component:
        name: app
      match:
        authority:
          exact: app.cantrip.art
        path:
          prefix: /
    - match:
        authority:
          exact: ${STARTER_DOMAIN}
        path:
          prefix: /
      redirect:
        authority: cantrip.art

static_sites:
  - name: app
    environment_slug: node-js
    build_command: pnpm --filter @cantrip/version build && pnpm --filter @cantrip/logging build && pnpm --filter @cantrip/protocol build && pnpm --filter @cantrip/crypto build && pnpm --filter @cantrip/app build
    github:
      branch: release
      deploy_on_push: true
      repo: ArcaneArts/Cantrip
    source_dir: /
    output_dir: cantrip_app/dist
    index_document: index.html
    catchall_document: index.html
  - name: site
    environment_slug: node-js
    build_command: pnpm --filter @cantrip/site build
    github:
      branch: release
      deploy_on_push: true
      repo: ArcaneArts/Cantrip
    source_dir: /
    output_dir: cantrip_site/dist
    index_document: index.html
    catchall_document: index.html
