//! ScreenCaptureKit stays on native callback lifetimes. No ObjC object crosses
//! the Rust channel; the executor receives owned metadata or bounded RGBA only.
mod accessibility;
mod click;
mod geometry;
mod pending;
mod registry;

use crate::{
    backend::{Capture, CaptureBackend, Raster, UnavailableBackend},
    cancellation::Cancellation,
    error::{CuaError, ErrorCode, Result},
    inventory::{MAX_TARGETS, TargetPage, prefix_len},
    target::{Bounds, Target, TargetKind},
};
use block2::RcBlock;
use dispatch2::DispatchQueue;
use objc2::{
    AnyThread,
    rc::{Retained, autoreleasepool},
    runtime::AnyClass,
    sel,
};
use objc2_core_foundation::{
    CFRetained, CFRunLoop, CFRunLoopSource, CFRunLoopSourceContext, CFUUID, kCFRunLoopDefaultMode,
};
use objc2_core_graphics::{
    CGDataProvider, CGImage, CGImageAlphaInfo, CGMainDisplayID, kCGColorSpaceSRGB,
};
use objc2_foundation::{NSArray, NSError, NSObject, NSUnderlyingErrorKey};
use objc2_screen_capture_kit::{
    SCContentFilter, SCDisplay, SCScreenshotManager, SCShareableContent, SCStreamConfiguration,
    SCStreamErrorDomain, SCWindow,
};
use pending::{NativeCalls, Pending};
use registry::{Candidate, Identity, Inventory, Registry};
use std::{
    collections::{BTreeMap, HashMap, HashSet},
    ptr::NonNull,
    sync::{
        Arc, OnceLock,
        atomic::{AtomicUsize, Ordering},
    },
};

fn diagnostic_entry() -> bool {
    static ENABLED: OnceLock<bool> = OnceLock::new();
    static LINES: AtomicUsize = AtomicUsize::new(0);
    *ENABLED.get_or_init(|| {
        std::env::var_os("CANTRIP_CUA_NATIVE_DIAGNOSTICS").is_some_and(|value| value == "1")
    }) && LINES
        .fetch_update(Ordering::Relaxed, Ordering::Relaxed, |count| {
            (count < 256).then_some(count + 1)
        })
        .is_ok()
}

fn diagnostic_phase(phase: &'static str) {
    if diagnostic_entry() {
        eprintln!("{{\"event\":\"cua.native.phase\",\"phase\":\"{phase}\"}}");
    }
}

fn diagnostic_inventory_count(kind: &'static str, count: usize) {
    if diagnostic_entry() {
        eprintln!(
            "{}",
            serde_json::json!({"event":"cua.native.inventory.count", "kind":kind, "count":count})
        );
    }
}

fn diagnostic_candidate_rejection(kind: &'static str, error: &CuaError) {
    if diagnostic_entry() {
        // These errors are generated by our metadata validation, not native
        // localized descriptions; they contain no target identifiers or titles.
        eprintln!(
            "{}",
            serde_json::json!({"event":"cua.native.inventory.rejected", "kind":kind, "code":error.code, "message":error.message})
        );
    }
}

fn diagnostic_native_error(error: &NSError) {
    if diagnostic_entry() {
        let info = error.userInfo();
        let keys = info.allKeys();
        let keys: Vec<_> = (0..keys.count().min(16))
            .map(|index| geometry::bounded_text(keys.objectAtIndex(index).to_string(), 80))
            .collect();
        let underlying = info.objectForKey(unsafe { NSUnderlyingErrorKey }).and_then(|value| value.downcast_ref::<NSError>().map(|error| serde_json::json!({"domain": geometry::bounded_text(error.domain().to_string(), 120), "code": error.code()})));
        // Keys and numeric/domain identity only. Never error descriptions,
        // arbitrary userInfo values, URLs, paths, titles or screenshot bytes.
        eprintln!(
            "{}",
            serde_json::json!({"event":"cua.native.error", "code":error.code(), "domain":geometry::bounded_text(error.domain().to_string(), 120), "keys":keys, "underlying":underlying})
        );
    }
}

// ColorSync exports this ownership-preserving display identity API. The
// returned Create reference
// is released by CFRetained after conversion to an internal UUID string.
#[link(name = "ColorSync", kind = "framework")]
unsafe extern "C-unwind" {
    fn CGDisplayCreateUUIDFromDisplayID(display: u32) -> Option<NonNull<CFUUID>>;
}

/// Availability describes the actual screenshot API, never a guessed TCC state.
pub fn available() -> bool {
    AnyClass::get(c"SCScreenshotManager").is_some_and(|class| {
        class
            .class_method(sel!(captureImageWithFilter:configuration:completionHandler:))
            .is_some()
    })
}

/// Binary entry point: the original main run loop remains serviced while one Rust
/// executor handles IPC. No windows, application activation or input.
pub fn run() -> std::io::Result<()> {
    if !available() {
        return crate::runtime::run(UnavailableBackend, std::io::stdin(), std::io::stdout());
    }
    // A command-line helper has no AppKit startup to initialize CoreGraphics
    // Services. Without this public display query on the original main thread,
    // SCContentFilter can abort in CGS_REQUIRE_INIT before returning an error.
    // The value is deliberately unused: this initializes the native runtime,
    // never preflights Screen Recording permission or rejects a capture target.
    let _ = CGMainDisplayID();
    let main_loop = CFRunLoop::current()
        .ok_or_else(|| std::io::Error::other("Native main run loop is unavailable."))?;
    // Preserve the original main thread and native event sources while idle,
    // with one unsignalled keepalive rather than timers or a busy loop.
    let mut context = CFRunLoopSourceContext {
        version: 0,
        info: std::ptr::null_mut(),
        retain: None,
        release: None,
        copyDescription: None,
        equal: None,
        hash: None,
        schedule: None,
        cancel: None,
        perform: None,
    };
    let keepalive = unsafe { CFRunLoopSource::new(None, 0, &mut context) }.ok_or_else(|| {
        std::io::Error::other("Native main run loop source could not be created.")
    })?;
    main_loop.add_source(Some(&keepalive), unsafe { kCFRunLoopDefaultMode });
    std::thread::Builder::new().name("cantrip-cua-executor".into()).spawn(|| {
        let result = crate::runtime::run(MacOsBackend::default(), std::io::stdin(), std::io::stdout());
        if result.is_err() {
            eprintln!("{{\"event\":\"cua.process.failed\",\"reason\":\"transport-or-runtime-failure\"}}");
        }
        // run() has already drained stdout and cancelled outstanding requests.
        // Process exit also releases any OS completion blocks which never
        // return after cancellation; it cannot strand the native main loop.
        std::process::exit(if result.is_ok() { 0 } else { 1 });
    })?;
    CFRunLoop::run();
    keepalive.invalidate();
    Err(std::io::Error::other(
        "Native main run loop stopped unexpectedly.",
    ))
}

#[derive(Default)]
pub struct MacOsBackend {
    calls: NativeCalls,
    accessibility: accessibility::Accessibility,
    registry: Registry,
    truncated: bool,
}

enum Selection {
    Page(Option<String>),
    Exact(String),
}

impl MacOsBackend {
    fn read_page(
        &mut self,
        selection: Selection,
        cancellation: &Cancellation,
    ) -> Result<TargetPage> {
        if !available() {
            return unsupported();
        }
        let (pending, receiver) = self.calls.begin(cancellation)?;
        let tracked = self.registry.tracked();
        let request = pending.clone();
        DispatchQueue::main().exec_async(move || {
            if request.cancelled() { return; }
            let completion = RcBlock::new(move |content: *mut SCShareableContent, error: *mut NSError| {
                diagnostic_phase("inventory-completion");
                if request.cancelled() { return; }
                autoreleasepool(|_| {
                    // SAFETY: SCK owns both nullable callback pointers until
                    // this callback returns. Only owned Rust values escape.
                    let result = unsafe { content_result(content, error).and_then(|content| read_inventory(content, &tracked, &selection, || request.cancelled())) };
                    request.deliver(result);
                });
            });
            // False onscreen-only includes occluded/offscreen candidates. Their
            // actual capture outcome, not visibility heuristics, is authoritative.
            diagnostic_phase("inventory-requested");
            unsafe { SCShareableContent::getShareableContentExcludingDesktopWindows_onScreenWindowsOnly_completionHandler(false, false, &completion); }
        });
        let (inventory, next_cursor) = pending.wait(&receiver)?;
        let (targets, truncated) = self.registry.update(inventory)?;
        self.truncated = truncated;
        Ok(TargetPage {
            targets,
            truncated,
            next_cursor,
        })
    }
}

impl CaptureBackend for MacOsBackend {
    fn click(
        &mut self,
        session: &str,
        target: &Target,
        position: crate::target::Point,
        cancel: &Cancellation,
    ) -> Result<(Target, crate::input::InputReceipt)> {
        self.accessibility
            .press_at(session, target, position, cancel)
    }
    fn global_click(
        &mut self,
        session: &str,
        target: &Target,
        position: crate::target::Point,
        cancel: &Cancellation,
    ) -> Result<(Target, crate::input::InputReceipt)> {
        self.accessibility.clear(session);
        click::click(target, position, cancel)
    }
    fn native_input(&self) -> bool {
        true
    }
    fn clear_controls(&mut self, session: &str) {
        self.accessibility.clear(session);
    }
    fn controls(
        &mut self,
        session: &str,
        target: &Target,
        cancel: &Cancellation,
    ) -> Result<crate::input::Controls> {
        self.accessibility.inspect(session, target, cancel)
    }
    fn press(
        &mut self,
        session: &str,
        target: &Target,
        reference: &str,
        cancel: &Cancellation,
    ) -> Result<crate::input::InputReceipt> {
        self.accessibility.press(session, target, reference, cancel)
    }

    fn name(&self) -> &'static str {
        "macos-screencapturekit"
    }
    fn available(&self) -> bool {
        available()
    }
    fn inventory_truncated(&self) -> bool {
        self.truncated
    }
    fn targets(&mut self, cancellation: &Cancellation) -> Result<Vec<Target>> {
        Ok(self.target_page(None, cancellation)?.targets)
    }
    fn target_page(
        &mut self,
        after: Option<&str>,
        cancellation: &Cancellation,
    ) -> Result<TargetPage> {
        if let Some(after) = after {
            crate::target::validate_id(after)?;
        }
        self.read_page(Selection::Page(after.map(str::to_owned)), cancellation)
    }
    fn resolve_target(
        &mut self,
        id: &str,
        generation: u64,
        cancellation: &Cancellation,
    ) -> Result<Target> {
        // Only an actually discovered incarnation may be attached. Refresh the
        // exact native identity independently of the public inventory page.
        self.registry.identity_for(id, generation)?;
        let page = self.read_page(Selection::Exact(id.to_owned()), cancellation)?;
        let target = page
            .targets
            .into_iter()
            .find(|target| target.id == id)
            .ok_or_else(|| {
                CuaError::new(ErrorCode::TargetNotFound, "CUA target no longer exists.")
            })?;
        self.registry.identity_for(id, generation)?;
        Ok(target)
    }
    fn capture(&mut self, target: &Target, cancellation: &Cancellation) -> Result<Capture> {
        if !available() {
            return unsupported();
        }
        let identity = self.registry.identity(target)?;
        let selected = target.clone();
        let (pending, receiver) = self.calls.begin(cancellation)?;
        let request = pending.clone();
        diagnostic_phase("capture-queued");
        DispatchQueue::main().exec_async(move || {
            if request.cancelled() { return; }
            let completion = RcBlock::new(move |content: *mut SCShareableContent, error: *mut NSError| {
                diagnostic_phase("capture-inventory-completion");
                if request.cancelled() { return; }
                autoreleasepool(|_| unsafe {
                    let source = content_result(content, error).and_then(|content| selected_filter(content, &selected, &identity));
                    match source {
                        Ok(source) => {
                            diagnostic_phase("selected-filter-ready");
                            begin_capture(source, request.clone());
                        },
                        Err(error) => request.deliver(Err(error)),
                    }
                });
            });
            diagnostic_phase("capture-inventory-requested");
            unsafe { SCShareableContent::getShareableContentExcludingDesktopWindows_onScreenWindowsOnly_completionHandler(false, false, &completion); }
        });
        let mut capture = match pending.wait(&receiver) {
            Ok(capture) => capture,
            Err(error) => {
                if matches!(
                    error.code,
                    ErrorCode::TargetNotFound | ErrorCode::StaleTarget
                ) {
                    self.registry.remove(&target.id);
                }
                return Err(error);
            }
        };
        cancellation.check()?;
        Ok(Capture {
            target: capture.target.clone(),
            raster: Raster {
                width: capture.target.pixel_width,
                height: capture.target.pixel_height,
                rgba: std::mem::take(&mut capture.rgba),
            },
        })
    }
}

struct NativeCapture {
    target: Target,
    rgba: Vec<u8>,
}
impl Drop for NativeCapture {
    fn drop(&mut self) {
        self.rgba.fill(0);
    }
}

fn unsupported<T>() -> Result<T> {
    Err(CuaError::new(
        ErrorCode::Unsupported,
        "Native CUA screenshots require macOS 14 or later.",
    ))
}

unsafe fn content_result<'a>(
    content: *mut SCShareableContent,
    error: *mut NSError,
) -> Result<&'a SCShareableContent> {
    if let Some(error) = unsafe { error.as_ref() } {
        return Err(native_error(error));
    }
    unsafe { content.as_ref() }.ok_or_else(|| {
        CuaError::new(
            ErrorCode::CaptureFailed,
            "macOS returned no capture inventory.",
        )
    })
}

fn native_error(error: &NSError) -> CuaError {
    diagnostic_native_error(error);
    let code = error.code();
    if &*error.domain() == unsafe { SCStreamErrorDomain } {
        match code {
            -3801 => {
                return CuaError::new(
                    ErrorCode::PermissionDenied,
                    "macOS denied Screen Recording access. Enable access for Cantrip in System Settings, then retry explicitly.",
                );
            }
            -3815 => {
                return CuaError::new(
                    ErrorCode::TargetNotFound,
                    "The selected native capture source is no longer available.",
                );
            }
            _ => {}
        }
    }
    // Deliberately omit localizedDescription/userInfo: they may include private
    // titles or paths. The numeric native error still identifies real failure.
    CuaError::new(
        ErrorCode::CaptureFailed,
        format!("macOS capture failed (native error {code})."),
    )
}

unsafe fn read_inventory(
    content: &SCShareableContent,
    tracked: &HashSet<String>,
    selection: &Selection,
    cancelled: impl Fn() -> bool,
) -> Result<(Inventory, Option<String>)> {
    let mut output = Inventory {
        candidates: vec![],
        present: HashMap::new(),
        truncated: false,
    };
    let mut candidates = BTreeMap::new();
    let mut more = false;
    // Walk the native NSArray without making an unbounded second handle vector.
    let displays = unsafe { content.displays() };
    diagnostic_inventory_count("display", displays.count());
    for index in 0..displays.count() {
        if cancelled() {
            return Err(CuaError::new(
                ErrorCode::Cancelled,
                "Native inventory was cancelled.",
            ));
        }
        let display = displays.objectAtIndex(index);
        match unsafe { display_candidate(&display, None) } {
            Ok(candidate) => add_candidate(
                &mut output,
                &mut candidates,
                &mut more,
                tracked,
                selection,
                candidate,
            )?,
            Err(error) => {
                diagnostic_candidate_rejection("display", &error);
                output.truncated = true;
                let native_id = unsafe { display.displayID() };
                let id = format!("macos-display-{native_id}");
                if tracked.contains(&id) {
                    output.present.insert(id, display_identity(native_id));
                }
            }
        }
    }
    let windows = unsafe { content.windows() };
    diagnostic_inventory_count("window", windows.count());
    for index in 0..windows.count() {
        if cancelled() {
            return Err(CuaError::new(
                ErrorCode::Cancelled,
                "Native inventory was cancelled.",
            ));
        }
        let window = windows.objectAtIndex(index);
        match unsafe { window_candidate(&window, None) } {
            Ok(candidate) => add_candidate(
                &mut output,
                &mut candidates,
                &mut more,
                tracked,
                selection,
                candidate,
            )?,
            Err(error) => {
                diagnostic_candidate_rejection("window", &error);
                output.truncated = true;
                let id = format!("macos-window-{}", unsafe { window.windowID() });
                if tracked.contains(&id) {
                    output
                        .present
                        .insert(id, unsafe { window_identity(&window) });
                }
            }
        }
    }
    finish_inventory(output, candidates, more)
}

fn finish_inventory(
    mut output: Inventory,
    candidates: BTreeMap<String, Candidate>,
    mut more: bool,
) -> Result<(Inventory, Option<String>)> {
    let count = prefix_len(
        candidates
            .values()
            .map(|candidate: &Candidate| &candidate.target),
    )?;
    more |= count < candidates.len();
    output.candidates = candidates.into_values().take(count).collect();
    for candidate in &output.candidates {
        output
            .present
            .insert(candidate.target.id.clone(), candidate.identity.clone());
    }
    let next_cursor = more.then(|| output.candidates.last().unwrap().target.id.clone());
    output.truncated |= more;
    Ok((output, next_cursor))
}

fn add_candidate(
    output: &mut Inventory,
    candidates: &mut BTreeMap<String, Candidate>,
    more: &mut bool,
    tracked: &HashSet<String>,
    selection: &Selection,
    candidate: Candidate,
) -> Result<()> {
    candidate.target.validate()?;
    let id = &candidate.target.id;
    if tracked.contains(id) {
        output
            .present
            .insert(id.clone(), candidate.identity.clone());
    }
    let include = match selection {
        Selection::Page(after) => after.as_ref().is_none_or(|after| id > after),
        Selection::Exact(selected) => id == selected,
    };
    if !include {
        return Ok(());
    }
    if candidates.contains_key(id) {
        return Err(CuaError::invalid("Duplicate native target identity."));
    }
    // Native order is not lexical. Keep only the smallest page plus one
    // lookahead; no unbounded metadata or retained ObjC handle vector.
    if candidates.len() < MAX_TARGETS + 1
        || candidates
            .last_key_value()
            .is_some_and(|(last, _)| id < last)
    {
        candidates.insert(id.clone(), candidate);
        if candidates.len() > MAX_TARGETS + 1 {
            candidates.pop_last();
            *more = true;
        }
    } else {
        *more = true;
    }
    Ok(())
}

struct SelectedSource {
    candidate: Candidate,
    filter: Retained<SCContentFilter>,
    native: Retained<NSObject>,
}

unsafe fn selected_filter(
    content: &SCShareableContent,
    selected: &Target,
    identity: &Identity,
) -> Result<SelectedSource> {
    let source = match selected.kind {
        TargetKind::Window => {
            let windows = unsafe { content.windows() };
            let window = (0..windows.count())
                .map(|index| windows.objectAtIndex(index))
                .find(|window| {
                    format!("macos-window-{}", unsafe { window.windowID() }) == selected.id
                })
                .ok_or_else(|| {
                    CuaError::new(
                        ErrorCode::TargetNotFound,
                        "The selected native window no longer exists.",
                    )
                })?;
            let filter = unsafe { window_filter(&window) }?;
            (
                unsafe { window_candidate(&window, Some(&filter)) }?,
                filter,
                window.into_super(),
            )
        }
        TargetKind::Monitor => {
            let displays = unsafe { content.displays() };
            let display = (0..displays.count())
                .map(|index| displays.objectAtIndex(index))
                .find(|display| {
                    format!("macos-display-{}", unsafe { display.displayID() }) == selected.id
                })
                .ok_or_else(|| {
                    CuaError::new(
                        ErrorCode::TargetNotFound,
                        "The selected native display no longer exists.",
                    )
                })?;
            let filter = unsafe {
                SCContentFilter::initWithDisplay_excludingWindows(
                    SCContentFilter::alloc(),
                    &display,
                    &NSArray::new(),
                )
            };
            (
                unsafe { display_candidate(&display, Some(&filter)) }?,
                filter,
                display.into_super(),
            )
        }
    };
    let (mut candidate, filter, native) = source;
    if &candidate.identity != identity {
        return Err(CuaError::new(
            ErrorCode::StaleTarget,
            "The selected native target changed owners.",
        ));
    }
    candidate.target.generation = selected.generation;
    Ok(SelectedSource {
        candidate,
        filter,
        native,
    })
}

unsafe fn candidate_geometry(
    filter: &SCContentFilter,
    x: f64,
    y: f64,
) -> Result<(Bounds, f64, u32, u32)> {
    let rect = unsafe { filter.contentRect() };
    let scale = f64::from(unsafe { filter.pointPixelScale() });
    let bounds = Bounds {
        x,
        y,
        width: rect.size.width,
        height: rect.size.height,
    };
    let (width, height) = geometry::output_size(bounds, scale)?;
    // Describe the actual output raster; Y scale can differ by one pixel of
    // rounding and is always independently derivable from height / bounds.
    Ok((bounds, f64::from(width) / bounds.width, width, height))
}

unsafe fn window_filter(window: &SCWindow) -> Result<objc2::rc::Retained<SCContentFilter>> {
    let frame = unsafe { window.frame() };
    geometry::native_frame(
        frame.origin.x,
        frame.origin.y,
        frame.size.width,
        frame.size.height,
    )?;
    Ok(unsafe {
        SCContentFilter::initWithDesktopIndependentWindow(SCContentFilter::alloc(), window)
    })
}

unsafe fn window_identity(window: &SCWindow) -> Identity {
    let app = unsafe { window.owningApplication() };
    Identity {
        process_id: app
            .as_ref()
            .and_then(|app| u32::try_from(unsafe { app.processID() }).ok()),
        application_id: app
            .as_ref()
            .map(|app| geometry::bounded_text(unsafe { app.bundleIdentifier() }.to_string(), 1024)),
    }
}

fn display_identity(id: u32) -> Identity {
    // Optional additional incarnation evidence, never capture eligibility.
    let uuid = unsafe { CGDisplayCreateUUIDFromDisplayID(id) }
        .map(|uuid| unsafe { CFRetained::from_raw(uuid) })
        .and_then(|uuid| CFUUID::new_string(None, Some(&uuid)))
        .map(|uuid| uuid.to_string());
    Identity {
        process_id: None,
        application_id: uuid,
    }
}

unsafe fn window_candidate(
    window: &SCWindow,
    filter: Option<&SCContentFilter>,
) -> Result<Candidate> {
    let frame = unsafe { window.frame() };
    let (bounds, scale_factor, pixel_width, pixel_height) = if let Some(filter) = filter {
        unsafe { candidate_geometry(filter, frame.origin.x, frame.origin.y) }?
    } else {
        geometry::inventory_geometry(
            frame.origin.x,
            frame.origin.y,
            frame.size.width,
            frame.size.height,
        )?
    };
    let app = unsafe { window.owningApplication() };
    let identity = unsafe { window_identity(window) };
    let process_id = identity.process_id;
    let target = Target {
        id: format!("macos-window-{}", unsafe { window.windowID() }),
        generation: 1,
        kind: TargetKind::Window,
        title: unsafe { window.title() }
            .map(|title| geometry::bounded_text(title.to_string(), 4096)),
        application: app
            .map(|app| geometry::bounded_text(unsafe { app.applicationName() }.to_string(), 1024)),
        process_id,
        bounds,
        pixel_width,
        pixel_height,
        scale_factor,
        focused: None,
        minimized: None,
    };
    target.validate()?;
    Ok(Candidate { target, identity })
}

unsafe fn display_candidate(
    display: &SCDisplay,
    filter: Option<&SCContentFilter>,
) -> Result<Candidate> {
    let frame = unsafe { display.frame() };
    let (bounds, scale_factor, pixel_width, pixel_height) = if let Some(filter) = filter {
        unsafe { candidate_geometry(filter, frame.origin.x, frame.origin.y) }?
    } else {
        geometry::inventory_geometry(
            frame.origin.x,
            frame.origin.y,
            frame.size.width,
            frame.size.height,
        )?
    };
    let id = unsafe { display.displayID() };
    let identity = display_identity(id);
    let target = Target {
        id: format!("macos-display-{id}"),
        generation: 1,
        kind: TargetKind::Monitor,
        title: Some(format!("Display {id}")),
        application: None,
        process_id: None,
        bounds,
        pixel_width,
        pixel_height,
        scale_factor,
        focused: None,
        minimized: None,
    };
    target.validate()?;
    Ok(Candidate { target, identity })
}

unsafe fn begin_capture(source: SelectedSource, pending: Arc<Pending<NativeCapture>>) {
    if pending.cancelled() {
        return;
    }
    let SelectedSource {
        candidate,
        filter,
        native,
    } = source;
    let config = unsafe { SCStreamConfiguration::new() };
    unsafe {
        config.setWidth(candidate.target.pixel_width as usize);
        config.setHeight(candidate.target.pixel_height as usize);
        config.setPixelFormat(u32::from_be_bytes(*b"BGRA"));
        config.setShowsCursor(false);
        config.setCapturesAudio(false);
        config.setIgnoreShadowsSingleWindow(true);
        config.setIgnoreGlobalClipSingleWindow(true);
        config.setScalesToFit(true);
        config.setPreservesAspectRatio(true);
        config.setColorSpaceName(kCGColorSpaceSRGB);
    }
    // Keep all native input objects alive until completion, including the
    // SCWindow/SCDisplay returned by the earlier shareable-content callback.
    // This is native block ownership, not an unsafe Send wrapper or Rust IPC.
    let keepalive = (filter.clone(), config.clone(), native);
    let completion = RcBlock::new(move |image: *mut CGImage, error: *mut NSError| {
        let _inputs = &keepalive;
        diagnostic_phase("image-callback");
        if pending.cancelled() {
            return;
        }
        autoreleasepool(|_| unsafe {
            let result = if let Some(error) = error.as_ref() {
                Err(native_error(error))
            } else if let Some(image) = image.as_ref() {
                read_pixels(image, &candidate.target, &pending)
            } else {
                Err(CuaError::new(
                    ErrorCode::CaptureFailed,
                    "macOS returned no screenshot pixels.",
                ))
            };
            pending.deliver(result);
        });
    });
    // SCK retains the completion block and its explicit input keepalive.
    diagnostic_phase("manager-called");
    unsafe {
        SCScreenshotManager::captureImageWithFilter_configuration_completionHandler(
            &filter,
            &config,
            Some(&completion),
        );
    }
    diagnostic_phase("manager-returned");
}

fn read_pixels(
    image: &CGImage,
    target: &Target,
    pending: &Pending<NativeCapture>,
) -> Result<NativeCapture> {
    let width = CGImage::width(Some(image));
    let height = CGImage::height(Some(image));
    let bitmap = CGImage::bitmap_info(Some(image)).0;
    let alpha = CGImage::alpha_info(Some(image));
    let component_bits = CGImage::bits_per_component(Some(image));
    let pixel_bits = CGImage::bits_per_pixel(Some(image));
    if width != target.pixel_width as usize
        || height != target.pixel_height as usize
        || component_bits != 8
        || pixel_bits != 32
        || bitmap & 0x7000 != 0x2000
        || !matches!(
            alpha,
            CGImageAlphaInfo::PremultipliedFirst
                | CGImageAlphaInfo::First
                | CGImageAlphaInfo::NoneSkipFirst
        )
    {
        return Err(CuaError::new(
            ErrorCode::CaptureFailed,
            format!(
                "macOS returned an unsupported screenshot layout (width={width}, height={height}, expected={}x{}, componentBits={component_bits}, pixelBits={pixel_bits}, bitmap=0x{bitmap:x}, alpha={}).",
                target.pixel_width, target.pixel_height, alpha.0,
            ),
        ));
    }
    let stride = CGImage::bytes_per_row(Some(image));
    geometry::native_storage_length(target.pixel_width, target.pixel_height, stride)?;
    let provider = CGImage::data_provider(Some(image)).ok_or_else(|| {
        CuaError::new(
            ErrorCode::CaptureFailed,
            "macOS screenshot has no pixel provider.",
        )
    })?;
    let data = CGDataProvider::data(Some(&provider)).ok_or_else(|| {
        CuaError::new(
            ErrorCode::CaptureFailed,
            "macOS screenshot pixels are unavailable.",
        )
    })?;
    // CopyData is immutable and owned exclusively here; no reference escapes.
    let bytes = unsafe { data.as_bytes_unchecked() };
    let rgba = geometry::bgra_to_rgba(
        bytes,
        target.pixel_width,
        target.pixel_height,
        stride,
        alpha == CGImageAlphaInfo::PremultipliedFirst,
        alpha == CGImageAlphaInfo::NoneSkipFirst,
        || pending.cancelled(),
    )?;
    Ok(NativeCapture {
        target: target.clone(),
        rgba,
    })
}

#[cfg(test)]
mod paging_tests {
    use super::*;
    use crate::backend::FakeBackend;
    fn source() -> Vec<Target> {
        let base = FakeBackend
            .targets(&Cancellation::default())
            .unwrap()
            .remove(0);
        (0..600)
            .rev()
            .map(|index| {
                let mut target = base.clone();
                target.id = format!("window-{index}");
                target
            })
            .collect()
    }
    fn collect(
        registry: &mut Registry,
        source: &[Target],
        selection: Selection,
        owner: u32,
    ) -> TargetPage {
        let tracked = registry.tracked();
        let mut output = Inventory {
            candidates: vec![],
            present: HashMap::new(),
            truncated: false,
        };
        let mut candidates = BTreeMap::new();
        let mut more = false;
        for target in source {
            add_candidate(
                &mut output,
                &mut candidates,
                &mut more,
                &tracked,
                &selection,
                Candidate {
                    target: target.clone(),
                    identity: Identity {
                        process_id: Some(owner),
                        application_id: Some("fixture".into()),
                    },
                },
            )
            .unwrap();
            assert!(candidates.len() <= MAX_TARGETS + 1);
            assert!(output.present.len() <= 4096);
        }
        let (inventory, next_cursor) = finish_inventory(output, candidates, more).unwrap();
        let (targets, truncated) = registry.update(inventory).unwrap();
        TargetPage {
            targets,
            truncated,
            next_cursor,
        }
    }
    #[test]
    fn native_selection_is_sorted_before_budgeting_and_exact_refresh_preserves_discovered_generation()
     {
        let source = source();
        let mut registry = Registry::default();
        let first = collect(&mut registry, &source, Selection::Page(None), 1);
        let expected = crate::inventory::page(source.clone(), None, false).unwrap();
        assert_eq!(
            first.targets.iter().map(|t| &t.id).collect::<Vec<_>>(),
            expected.targets.iter().map(|t| &t.id).collect::<Vec<_>>()
        );
        let second = collect(
            &mut registry,
            &source,
            Selection::Page(first.next_cursor.clone()),
            1,
        );
        let discovered = second.targets.last().unwrap().clone();
        assert!(
            !first
                .targets
                .iter()
                .any(|target| target.id == discovered.id)
        );
        collect(&mut registry, &source, Selection::Page(None), 1);
        assert!(
            registry
                .identity_for(&discovered.id, discovered.generation)
                .is_ok()
        );
        let exact = collect(
            &mut registry,
            &source,
            Selection::Exact(discovered.id.clone()),
            1,
        );
        assert_eq!(exact.targets.len(), 1);
        assert_eq!(exact.targets[0].generation, discovered.generation);
        assert!(exact.next_cursor.is_none());
        assert!(
            registry
                .identity_for(&discovered.id, discovered.generation + 1)
                .is_err()
        );
        collect(
            &mut registry,
            &source,
            Selection::Exact(discovered.id.clone()),
            2,
        );
        assert!(
            registry
                .identity_for(&discovered.id, discovered.generation)
                .is_err()
        );
        let renewed = collect(
            &mut registry,
            &source,
            Selection::Exact(discovered.id.clone()),
            2,
        )
        .targets
        .remove(0);
        let missing: Vec<_> = source
            .into_iter()
            .filter(|target| target.id != discovered.id)
            .collect();
        assert!(
            collect(
                &mut registry,
                &missing,
                Selection::Exact(discovered.id.clone()),
                2
            )
            .targets
            .is_empty()
        );
        assert!(
            registry
                .identity_for(&renewed.id, renewed.generation)
                .is_err()
        );
    }
}
