/** Explicit inventory for pinned Codex 0.153.4 + the reviewed Cantrip patches.
 * Unknown methods fail closed; a known mutation still requires admission.
 * Read labels describe authority, not whether native discovery allocates clients.
 */
export type ManagedNativeMethodKind =
  | "read"
  | "attach"
  | "start"
  | "control"
  | "settings"
  | "defaults"
  | "mutation";

const groups: Record<ManagedNativeMethodKind, readonly string[]> = {
  read: [
    "initialize",
    "server/diagnostics",
    "thread/goal/get",
    "thread/queue/list",
    "thread/backgroundTerminals/list",
    "thread/list",
    "thread/loaded/list",
    "thread/read",
    "thread/turns/list",
    "thread/items/list",
    "thread/search",
    "thread/searchOccurrences",
    "thread/timeline/list",
    "thread/realtime/listVoices",
    "model/list",
    "modelProvider/capabilities/read",
    "collaborationMode/list",
    "experimentalFeature/list",
    "permissionProfile/list",
    "config/read",
    "configRequirements/read",
    "account/read",
    "account/rateLimits/read",
    "account/usage/read",
    "account/workspaceMessages/read",
    "getAuthStatus",
  ],
  attach: ["thread/resume", "thread/unsubscribe"],
  start: [
    "turn/start",
    "review/start",
    "thread/compact/start",
    "thread/shellCommand",
    "thread/realtime/start",
  ],
  control: [
    "turn/interrupt",
    "turn/pause",
    "turn/steer",
    "thread/realtime/stop",
    "thread/realtime/appendAudio",
    "thread/realtime/appendText",
    "thread/realtime/appendSpeech",
  ],
  settings: [
    "thread/settings/update",
    "turn/settings/update",
    "thread/managedConfig/update",
  ],
  defaults: [
    "config/value/write",
    "config/batchWrite",
    "config/mcpServer/reload",
    "experimentalFeature/enablement/set",
    "skills/config/write",
    "skills/extraRoots/set",
  ],
  mutation: [
    "thread/start",
    "thread/fork",
    "thread/archive",
    "thread/delete",
    "thread/increment_elicitation",
    "thread/decrement_elicitation",
    "thread/name/set",
    "thread/goal/set",
    "thread/goal/clear",
    "thread/queue/add",
    "thread/queue/start",
    "thread/queue/update",
    "thread/queue/delete",
    "thread/queue/reorder",
    "thread/metadata/update",
    "thread/section/move",
    "thread/memoryMode/set",
    "memory/reset",
    "thread/unarchive",
    "thread/approveGuardianDeniedAction",
    "thread/backgroundTerminals/clean",
    "thread/backgroundTerminals/terminate",
    "thread/rollback",
    "thread/revert",
    "thread/inject_items",
    "project/list",
    "project/read",
    "project/create",
    "project/import",
    "project/update",
    "project/move",
    "project/delete",
    "threadSection/list",
    "threadSection/create",
    "threadSection/update",
    "threadSection/delete",
    "skills/list",
    "hooks/list",
    "marketplace/add",
    "marketplace/remove",
    "marketplace/upgrade",
    "plugin/list",
    "plugin/search",
    "plugin/installed",
    "plugin/reconcile",
    "plugin/read",
    "plugin/skill/read",
    "plugin/share/save",
    "plugin/share/updateTargets",
    "plugin/share/list",
    "plugin/share/checkout",
    "plugin/share/delete",
    "app/read",
    "app/list",
    "app/installed",
    "fs/readFile",
    "fs/writeFile",
    "fs/createDirectory",
    "fs/getMetadata",
    "fs/readDirectory",
    "fs/remove",
    "fs/copy",
    "fs/watch",
    "fs/unwatch",
    "plugin/install",
    "plugin/uninstall",
    "remoteControl/enable",
    "remoteControl/disable",
    "remoteControl/status/read",
    "remoteControl/pairing/start",
    "remoteControl/pairing/status",
    "remoteControl/client/list",
    "remoteControl/client/revoke",
    "mock/experimentalMethod",
    "environment/add",
    "environment/info",
    "environment/status",
    "mcpServer/oauth/login",
    "mcpServerStatus/list",
    "mcpServer/resource/read",
    "mcpServer/event/stream/start",
    "mcpServer/event/stream/stop",
    "mcpServer/tool/call",
    "windowsSandbox/setupStart",
    "windowsSandbox/readiness",
    "account/login/start",
    "account/bedrock/discover",
    "account/bedrock/setup",
    "account/login/cancel",
    "account/logout",
    "account/rateLimitResetCredit/consume",
    "account/sendAddCreditsNudgeEmail",
    "feedback/upload",
    "command/exec",
    "command/exec/write",
    "command/exec/terminate",
    "command/exec/resize",
    "process/spawn",
    "process/writeStdin",
    "process/kill",
    "process/resizePty",
    "externalAgentConfig/detect",
    "externalAgentConfig/import",
    "externalAgentConfig/import/recordHistory",
    "externalAgentConfig/import/readHistories",
    "getConversationSummary",
    "gitDiffToRemote",
    "fuzzyFileSearch",
    "fuzzyFileSearch/sessionStart",
    "fuzzyFileSearch/sessionUpdate",
    "fuzzyFileSearch/sessionStop",
  ],
};

export const managedNativeMethods: ReadonlyMap<
  string,
  ManagedNativeMethodKind
> = new Map(
  Object.entries(groups).flatMap(([kind, methods]) =>
    methods.map((method) => [method, kind as ManagedNativeMethodKind] as const),
  ),
);

export const managedNativeServerRequests = new Set([
  "item/commandExecution/requestApproval",
  "item/fileChange/requestApproval",
  "item/tool/requestUserInput",
  "mcpServer/elicitation/request",
  "item/permissions/requestApproval",
  "item/tool/call",
  "account/chatgptAuthTokens/refresh",
  "attestation/generate",
  "currentTime/read",
]);

export const classifyManagedNativeMethod = (
  method: string,
): ManagedNativeMethodKind | null => managedNativeMethods.get(method) ?? null;
