export type {
  GithubAuthStatus,
  GithubRepository,
  GithubRepositoryOwner,
  GithubRepositoryVisibility,
  GithubRepositoryCreate,
  GithubIssueState,
  GithubIssueKind,
  GithubIssueSummary,
  GithubIssueList,
  GithubPullRequestList,
  GithubIssueComment,
  GithubIssueDetail,
  GithubIssueCreate,
  GithubPullRequestCreate,
  GithubPullRequestSummary,
  GithubPullRequestCreateResult,
  GithubPullRequestCommit,
  GithubPullRequestFile,
  GithubPullRequestCheck,
  GithubPullRequestReview,
  GithubPullRequestReviewComment,
  GithubPullRequestReviewThread,
  GithubPullRequestReviewSubmit,
  GithubPullRequestInlineCommentCreate,
  GithubPullRequestReviewAction,
  GithubPullRequestLifecycleAction,
  GithubPullRequestLifecyclePreview,
  GithubPullRequestLifecycleApply,
  GithubPullRequestCheckoutPrepared,
  GithubPullRequestDetail,
  GithubReleaseSummary,
  GithubReleaseList,
  GithubReleaseCreate,
} from "./github.js";

export {
  projectOriginKindSchema,
  projectFolderManagementSchema,
  projectSourceKindSchema,
  projectRootKindSchema,
  projectCapabilitiesSchema,
  projectCapabilitySchema,
  projectCapabilityUnavailableErrorSchema,
  projectCapabilitiesForOriginKind,
} from "./project-foundation.js";

export type {
  ProjectOriginKind,
  ProjectFolderManagement,
  ProjectSourceKind,
  ProjectRootKind,
  ProjectCapabilities,
  ProjectCapability,
  ProjectCapabilityUnavailableError,
} from "./project-foundation.js";

export {
  projectGithubConversionRepositorySchema,
  projectGithubRoutingRepositorySchema,
  projectGithubWireRepositorySchema,
  projectReplicaPlacementModeSchema,
  projectReplicaPlacementRequestSchema,
  encryptedProjectReplicaPlacementRequestSchema,
  projectReplicaMaterializationSchema,
  projectReplicaOwnershipKindSchema,
  projectReplicaPlacementResultSchema,
  githubProjectCreateSchema,
  encryptedGithubProjectCreateSchema,
  managedFolderProjectCreateSchema,
  encryptedManagedFolderProjectCreateSchema,
  projectWorkspaceStorageKindSchema,
  projectWorkspaceStorageCreateSchema,
  encryptedProjectWorkspaceStorageCreateSchema,
  projectWorkspaceStorageProfileSchema,
  projectWorkspaceStorageContextSchema,
  projectWorkspaceStorageCanBeDefault,
  projectWorkspaceCreateSchema,
  projectWorkspaceUpdateSchema,
  encryptedProjectWorkspaceNameSchema,
  systemDefaultProjectWorkspaceNameSchema,
  projectWorkspaceWireSummarySchema,
  projectWorkspaceWireListSchema,
  encryptedProjectWorkspaceCreateSchema,
  encryptedAttachedProjectWorkspaceCreateSchema,
  encryptedAttachedProjectWorkspaceCreateResultSchema,
  encryptedProjectWorkspaceUpdateSchema,
  projectWorkspaceSummarySchema,
  projectWorkspaceListSchema,
  projectSourceSummarySchema,
  projectReplicaSummarySchema,
  projectReplicaListSchema,
  projectReplicaJobKindSchema,
  projectReplicaJobStateSchema,
  projectReplicaJobErrorCodeSchema,
  projectReplicaJobErrorSchema,
  projectReplicaJobProgressStageSchema,
  projectReplicaJobProgressSchema,
  projectReplicaJobProgressEventSchema,
  projectReplicaJobSummarySchema,
  projectReplicaJobListSchema,
  projectReplicaProvisionCreateSchema,
  encryptedProjectReplicaProvisionCreateSchema,
  projectReplicaSynchronizationPolicySchema,
  projectReplicaSynchronizeCreateSchema,
  encryptedProjectReplicaSynchronizeCreateSchema,
  projectReplicaRemoveCreateSchema,
  encryptedProjectReplicaRemoveCreateSchema,
  projectReplicaJobRetrySchema,
  projectReplicaJobCancelSchema,
  projectSetupStatusSchema,
  projectSummarySchema,
  projectWireSummarySchema,
  projectListSchema,
  projectWireListSchema,
  projectPreferredWorkerUpdateSchema,
} from "./projects.js";

export {
  workspaceRepositoryDiscoveryJobStateSchema,
  workspaceRepositoryDiscoveryErrorCodeSchema,
  workspaceRepositoryDiscoveryErrorSchema,
  workspaceRepositoryDiscoveryCountsSchema,
  workspaceRepositoryDiscoveryProgressSchema,
  workspaceRepositoryDiscoveryJobSummarySchema,
  workspaceRepositoryCandidateClassificationSchema,
  workspaceRepositoryCandidateImportStateSchema,
  workspaceRepositoryCandidateSummarySchema,
  workspaceRepositoryDiscoverySnapshotSchema,
  workspaceRepositoryDiscoveryStartSchema,
  workspaceRepositoryDiscoveryCommandSchema,
  workspaceRepositoryDiscoveryWorkerResultSchema,
} from "./workspace-repository-discovery.js";

export type {
  WorkspaceRepositoryDiscoveryJobState,
  WorkspaceRepositoryDiscoveryErrorCode,
  WorkspaceRepositoryDiscoveryError,
  WorkspaceRepositoryDiscoveryCounts,
  WorkspaceRepositoryDiscoveryProgress,
  WorkspaceRepositoryDiscoveryJobSummary,
  WorkspaceRepositoryCandidateClassification,
  WorkspaceRepositoryCandidateImportState,
  WorkspaceRepositoryCandidateSummary,
  WorkspaceRepositoryDiscoverySnapshot,
  WorkspaceRepositoryDiscoveryStart,
  WorkspaceRepositoryDiscoveryCommand,
  WorkspaceRepositoryDiscoveryWorkerResult,
} from "./workspace-repository-discovery.js";

export type {
  ProjectReplicaPlacementMode,
  ProjectReplicaPlacementRequest,
  EncryptedProjectReplicaPlacementRequest,
  ProjectReplicaMaterialization,
  ProjectReplicaOwnershipKind,
  ProjectReplicaPlacementResult,
  ProjectSummary,
  ProjectWireSummary,
  ProjectPreferredWorkerUpdate,
  ProjectReplicaSummary,
  ProjectReplicaJobKind,
  ProjectReplicaJobState,
  ProjectReplicaJobErrorCode,
  ProjectReplicaJobError,
  ProjectReplicaJobProgress,
  ProjectReplicaJobProgressEvent,
  ProjectReplicaJobSummary,
  ProjectReplicaProvisionCreate,
  EncryptedProjectReplicaProvisionCreate,
  ProjectReplicaSynchronizationPolicy,
  ProjectReplicaSynchronizeCreate,
  EncryptedProjectReplicaSynchronizeCreate,
  ProjectReplicaRemoveCreate,
  EncryptedProjectReplicaRemoveCreate,
  ProjectReplicaJobRetry,
  ProjectReplicaJobCancel,
  ProjectWorkspaceCreate,
  ProjectWorkspaceStorageKind,
  ProjectWorkspaceStorageCreate,
  EncryptedProjectWorkspaceStorageCreate,
  ProjectWorkspaceStorageProfile,
  ProjectWorkspaceStorageContext,
  ProjectWorkspaceUpdate,
  ProjectWorkspaceSummary,
  EncryptedProjectWorkspaceName,
  ProjectWorkspaceWireSummary,
  ProjectWorkspaceWireList,
  EncryptedProjectWorkspaceCreate,
  EncryptedAttachedProjectWorkspaceCreate,
  EncryptedAttachedProjectWorkspaceCreateResult,
  EncryptedProjectWorkspaceUpdate,
  GithubProjectCreate,
  EncryptedGithubProjectCreate,
  ManagedFolderProjectCreate,
  EncryptedManagedFolderProjectCreate,
  ProjectGithubConversionRepository,
  ProjectGithubRoutingRepository,
} from "./projects.js";

export {
  executionSurfaceKindSchema,
  executionPlacementSchema,
  executionTargetSchema,
  executionPlacementSelectionSchema,
  executionPlacementResolveRequestSchema,
  executionPlacementResolutionSchema,
  executionTargetResourceKindSchema,
  executionTargetAvailabilitySchema,
  executionTargetResolutionSchema,
  executionTargetResolveRequestSchema,
  executionTargetDescriptorSchema,
  executionTargetWireDescriptorSchema,
  executionTargetCatalogSchema,
  executionTargetWireCatalogSchema,
} from "./execution-targets.js";

export type {
  ExecutionSurfaceKind,
  ExecutionPlacement,
  ExecutionTarget,
  ExecutionPlacementSelection,
  ExecutionPlacementResolveRequest,
  ExecutionPlacementResolution,
  ExecutionTargetResourceKind,
  ExecutionTargetAvailability,
  ExecutionTargetResolution,
  ExecutionTargetResolveRequest,
  ExecutionTargetDescriptor,
  ExecutionTargetWireDescriptor,
  ExecutionTargetCatalog,
  ExecutionTargetWireCatalog,
} from "./execution-targets.js";

export {
  worktreePolicySchema,
  worktreeOriginSchema,
  worktreeLifecycleStateSchema,
  projectWorktreeSummarySchema,
  projectWorktreeListSchema,
  githubPullRequestCheckoutResultSchema,
} from "./worktrees.js";

export type {
  WorktreePolicy,
  WorktreeOrigin,
  WorktreeLifecycleState,
  ProjectWorktreeSummary,
  GithubPullRequestCheckoutResult,
} from "./worktrees.js";

export {
  tunnelOriginSchema,
  tunnelManagementSchema,
  tunnelProtocolHintSchema,
  tunnelDesiredStateSchema,
  tunnelStatusSchema,
  tunnelWorkerHostSchema,
  tunnelSourceEndpointSchema,
  tunnelDestinationEndpointSchema,
  tunnelManagedResourceSchema,
  tunnelUserCreateSchema,
  tunnelUserUpdateSchema,
  tunnelUserWireCreateSchema,
  tunnelUserWireUpdateSchema,
  tunnelManagedRegistrationSchema,
  tunnelAttachmentKindSchema,
  tunnelAttachmentSummarySchema,
  tunnelAttachmentWireSummarySchema,
  tunnelAttachmentCreateSchema,
  tunnelAttachmentCreateResultSchema,
  tunnelDirectActivationSchema,
  tunnelAttachmentInitializeSchema,
  tunnelAttachmentReadySchema,
  tunnelActionCapabilitiesSchema,
  tunnelSummarySchema,
  tunnelListSchema,
  tunnelWireSummarySchema,
  tunnelWireListSchema,
} from "./tunnels.js";

export type {
  TunnelOrigin,
  TunnelManagement,
  TunnelProtocolHint,
  TunnelDesiredState,
  TunnelStatus,
  TunnelSourceEndpoint,
  TunnelDestinationEndpoint,
  TunnelManagedResource,
  TunnelUserCreate,
  TunnelUserUpdate,
  TunnelUserWireCreate,
  TunnelUserWireUpdate,
  TunnelAttachmentCreate,
  TunnelAttachmentCreateResult,
  TunnelAttachmentInitialize,
  TunnelAttachmentReady,
  TunnelManagedRegistration,
  TunnelAttachmentKind,
  TunnelAttachmentSummary,
  TunnelAttachmentWireSummary,
  TunnelActionCapabilities,
  TunnelSummary,
  TunnelWireSummary,
} from "./tunnels.js";

export {
  projectGitRepositoryStatsSchema,
  projectFolderStatsSchema,
  projectRepositoryStatsSchema,
  projectTokenUsageDaySchema,
  projectTokenUsageBreakdownSchema,
  projectTokenUsageSchema,
  telemetryValueStatisticsSchema,
  telemetryQuotaReadingSchema,
  telemetryQuotaReadingWireSchema,
  telemetryBreakdownSchema,
  telemetryBreakdownWireSchema,
  modelBehaviorSummarySchema,
  modelBehaviorBreakdownSchema,
  modelBehaviorDaySchema,
  telemetryChangeMetricSchema,
  telemetryChangePointSchema,
  telemetryChangePointWireSchema,
  providerTelemetryAnalyticsSchema,
  providerTelemetryWireAnalyticsSchema,
  providerTelemetryExportSchema,
  providerTelemetryDeleteResultSchema,
} from "./telemetry.js";

export type {
  ProjectRepositoryStats,
  ProjectGitRepositoryStats,
  ProjectFolderStats,
  ProjectTokenUsageDay,
  ProjectTokenUsageBreakdown,
  ProjectTokenUsage,
  TelemetryValueStatistics,
  TelemetryQuotaReading,
  TelemetryBreakdown,
  ModelBehaviorSummary,
  TelemetryChangeMetric,
  TelemetryChangePoint,
  ProviderTelemetryAnalytics,
  ProviderTelemetryWireAnalytics,
  ProviderTelemetryExport,
  ProviderTelemetryDeleteResult,
} from "./telemetry.js";

export {
  chatCreateSchema,
  encryptedChatCreateSchema,
  taskCreateSchema,
  encryptedTaskCreateSchema,
  chatUpdateSchema,
  encryptedChatUpdateSchema,
  chatForkSchema,
  encryptedChatForkSchema,
  orderedIdsSchema,
  chatContextKindSchema,
  projectChatExecutionRootSchema,
  standaloneChatExecutionRootSchema,
  chatExecutionRootSchema,
  standaloneChatRootStatusSchema,
  standaloneChatRootSummarySchema,
  standaloneChatIdentitySchema,
  standaloneChatCreateSchema,
  encryptedStandaloneChatCreateSchema,
  standaloneChatRootJobKindSchema,
  standaloneChatRootJobStateSchema,
  standaloneChatRootJobErrorSchema,
  standaloneChatRootJobSummarySchema,
  standaloneChatScratchProvisionResultSchema,
  standaloneChatScratchResolveResultSchema,
  standaloneChatScratchDeleteResultSchema,
  standaloneChatScratchArchiveResultSchema,
  standaloneChatScratchReconciliationTargetSchema,
  standaloneChatScratchReconciliationInventorySchema,
  standaloneChatScratchReconciliationResultSchema,
  projectChatSummarySchema,
  standaloneChatSummarySchema,
  contextualChatSummarySchema,
  chatSummarySchema,
  projectChatWireSummarySchema,
  standaloneChatWireSummarySchema,
  contextualChatWireSummarySchema,
  chatWireSummarySchema,
  taskCreateResultSchema,
  taskWireCreateResultSchema,
  chatListSchema,
  chatWireListSchema,
  archivedProjectChatSummarySchema,
  archivedStandaloneChatSummarySchema,
  contextualArchivedChatSummarySchema,
  archivedChatSummarySchema,
  archivedProjectChatWireSummarySchema,
  archivedStandaloneChatWireSummarySchema,
  contextualArchivedChatWireSummarySchema,
  archivedChatWireSummarySchema,
  archivedChatListSchema,
  archivedChatWireListSchema,
  archivedChatCleanupResultSchema,
} from "./chats.js";

export type {
  StandaloneChatRootJobKind,
  StandaloneChatRootJobState,
  StandaloneChatRootJobError,
  StandaloneChatRootJobSummary,
  StandaloneChatScratchProvisionResult,
  StandaloneChatScratchResolveResult,
  StandaloneChatScratchDeleteResult,
  StandaloneChatScratchArchiveResult,
  StandaloneChatScratchReconciliationTarget,
  StandaloneChatScratchReconciliationResult,
  ChatCreate,
  EncryptedChatCreate,
  StandaloneChatCreate,
  EncryptedStandaloneChatCreate,
  TaskCreate,
  EncryptedTaskCreate,
  TaskCreateResult,
  TaskWireCreateResult,
  ChatUpdate,
  EncryptedChatUpdate,
  ChatFork,
  EncryptedChatFork,
  OrderedIds,
  ChatContextKind,
  ProjectChatExecutionRoot,
  StandaloneChatExecutionRoot,
  ChatExecutionRoot,
  StandaloneChatRootStatus,
  StandaloneChatRootSummary,
  ProjectChatSummary,
  StandaloneChatSummary,
  ProjectChatWireSummary,
  StandaloneChatWireSummary,
  ContextualChatSummary,
  ContextualChatWireSummary,
  ChatSummary,
  ChatWireSummary,
  ArchivedChatSummary,
  ArchivedChatWireSummary,
  ArchivedStandaloneChatSummary,
  ArchivedStandaloneChatWireSummary,
  ArchivedChatCleanupResult,
} from "./chats.js";

export {
  permissionProfileIdSchema,
  YOLO_PERMISSION_PROFILE_ID,
  permissionProfileSummarySchema,
  permissionProfileCapabilitySchema,
  chatPermissionProfileStateSchema,
  chatPermissionProfileUpdateSchema,
} from "./permission-profiles.js";

export type {
  PermissionProfileSummary,
  PermissionProfileCapability,
  ChatPermissionProfileState,
  ChatPermissionProfileUpdate,
} from "./permission-profiles.js";

export { repositoryRelativePathSchema } from "./repository-paths.js";

export {
  terminalCreateSchema,
  encryptedTerminalCreateSchema,
  encryptedLinkedConsoleCreateSchema,
  terminalUpdateSchema,
  encryptedTerminalUpdateSchema,
  terminalServiceConfigurationSchema,
  encryptedTerminalServiceConfigurationSchema,
  terminalServiceRuntimeConfigurationSchema,
  terminalKindSchema,
  terminalSummarySchema,
  terminalWireSummarySchema,
  terminalListSchema,
  terminalWireListSchema,
  scriptCommandKindSchema,
  scriptCommandSchema,
  scriptCommandListSchema,
  protectedScriptCommandListSchema,
  terminalClientMessageSchema,
  terminalHydrationMetadataSchema,
  terminalServerMessageSchema,
  terminalOpenResultSchema,
  terminalSnapshotResultSchema,
} from "./terminals.js";

export type {
  TerminalCreate,
  EncryptedTerminalCreate,
  TerminalUpdate,
  EncryptedTerminalUpdate,
  TerminalServiceConfiguration,
  EncryptedTerminalServiceConfiguration,
  TerminalServiceRuntimeConfiguration,
  TerminalSummary,
  TerminalWireSummary,
  TerminalKind,
  ScriptCommandKind,
  ScriptCommand,
  TerminalClientMessage,
  TerminalHydrationMetadata,
  TerminalServerMessage,
  TerminalOpenResult,
  TerminalSnapshotResult,
} from "./terminals.js";

export {
  explorerFileModeSchema,
  explorerCreateSchema,
  encryptedExplorerCreateSchema,
  explorerUpdateSchema,
  encryptedExplorerUpdateSchema,
  encryptedExplorerPinSchema,
  explorerViewStateUpdateSchema,
  encryptedExplorerViewStateUpdateSchema,
  encryptedExplorerWorktreeUpdateSchema,
  explorerSummarySchema,
  explorerWireSummarySchema,
  explorerListSchema,
  explorerWireListSchema,
} from "./explorer-surfaces.js";

export type {
  ExplorerCreate,
  EncryptedExplorerCreate,
  ExplorerUpdate,
  EncryptedExplorerUpdate,
  EncryptedExplorerPin,
  ExplorerFileMode,
  ExplorerViewStateUpdate,
  EncryptedExplorerViewStateUpdate,
  EncryptedExplorerWorktreeUpdate,
  ExplorerSummary,
  ExplorerWireSummary,
} from "./explorer-surfaces.js";

export {
  codeThemeModeSchema,
  codePresentationSchema,
  codeAppearanceSchema,
  codeTabStatusSchema,
  codeSessionStatusSchema,
  codeTabCreateSchema,
  encryptedCodeTabCreateSchema,
  codeTabUpdateSchema,
  encryptedCodeTabUpdateSchema,
  codeTabSummarySchema,
  codeTabWireSummarySchema,
  codeTabListSchema,
  codeTabWireListSchema,
  codeEditorBuildSchema,
  codeProbeResultSchema,
  codeSessionSummarySchema,
  codeSessionListSchema,
  codeDirtyEditorSchema,
  codeSaveBeforeAgentTurnSchema,
  codeWorkbenchAgentStatusSchema,
  codeWorkbenchActiveEditorSchema,
  codeWorkbenchGitStateSchema,
  codeWorkbenchStateSchema,
  codeRuntimeStatusSchema,
  codeSettingsWorkbenchOpenResultSchema,
  codeSaveAllResultSchema,
  codeAgentTurnPreparationSessionSchema,
  codeAgentTurnPreparationResultSchema,
  codeAgentTurnNotificationResultSchema,
  codeAttachmentSchema,
  codeProtectedAttachmentWireSchema,
  codeProtectedAttachmentIntentSchema,
  codeSessionRouteGrantSchema,
  codeSessionRouteBasePath,
  parseCodeSessionRoutePath,
  codeTransportCandidateSchema,
  codeTransportWireSchema,
  codeSessionAttachmentWireSchema,
  codeSharedAttachmentWireSchema,
  codeTransportRouteAuthorizeCommandSchema,
  codeTransportRouteRevokeCommandSchema,
  codeTransportRevokeCommandSchema,
  codeTransportRouteAuthorizeResultSchema,
  codeTransportRouteRevokeResultSchema,
  codeTransportRevokeResultSchema,
  projectShareAttachmentSchema,
  PROJECT_SHARE_STATE_STALE_CODE,
  projectShareTunnelCreateSchema,
  projectShareDirectCreateSchema,
  projectShareAttachmentWireSchema,
  standaloneChatShareAttachmentSchema,
  standaloneChatShareAttachmentWireSchema,
  projectSharePublicBasePathSchema,
  projectSharePublicOriginSchema,
  codeAttachmentCreateSchema,
  codeProtectedAttachmentCreateSchema,
  codeSessionAttachmentCreateSchema,
  explorerCodeSessionAttachmentCreateSchema,
  codeSettingsWorkbenchSessionAttachmentCreateSchema,
  codeSettingsWorkbenchSharedAttachmentWireSchema,
  explorerCodeProtectedAttachmentCreateSchema,
  codeSettingsWorkbenchAttachmentCreateSchema,
  codeSettingsWorkbenchAttachmentWireSchema,
  explorerCodeAttachmentCreateSchema,
  codeOpenFileResultSchema,
  codeOpenFileRequestSchema,
  codeOpenSettingsRequestSchema,
  codeOpenSettingsResultSchema,
  codeOpenExtensionsRequestSchema,
  codeOpenExtensionsResultSchema,
  codeInstallVsixResultSchema,
  codePresentationUpdateSchema,
  codeThemeUpdateSchema,
  isForwardableCodeWebSocketCloseCode,
  CODE_MAX_WEBSOCKET_MESSAGE_BYTES,
} from "./code-surfaces.js";
