/** Entry point shared by the normal Cantrip surface and dedicated CUA host. */
export const CUA_DISCOVERY_GUIDANCE =
  'Desktop computer use is provided by Cantrip\'s managed `cantrip_cua` MCP server, with tools `js` and `js_reset`. For requests to inspect or interact with a running application, discover `cantrip_cua` specifically (including deferred tools); its namespace is separate from `cantrip`. Start by calling its `js` tool with {"script":"await cua.targets()"}. An empty `cantrip.target_list` remote-desktop/remote-surface list says nothing about native CUA windows. Do not use that registry, `cantrip -h`, AppleScript/osascript, shell automation, or browser-service targets as a substitute for Cantrip CUA. If the CUA tools are actually unavailable, report that tool-registration problem; do not ask the user to create or authorize a remote-desktop target.';

export const CUA_START_GUIDANCE =
  "Read the returned target pages, select the intended application window by its current metadata, then call cua.attach({targetId: target.id, targetGeneration: target.generation}) and cua.snapshot(). Use identifiers from the returned inventory; attach again in each new agent turn. For an ordinary authorized click, inspect cua.controls() or cua.controls({x,y}), match the intended control, and use cua.press(reference) or cua.click({x,y}); then take a fresh snapshot to assess the actual result. The custom cursor uses window-local coordinates. Window sharing starts automatically during capture, including for covered windows; there is no separate sharing command or remote-desktop setup. Preserve the human pointer and foreground: never select globalClick implicitly, and never retry or switch input methods after an unknown outcome. Follow the CUA tool documentation for detailed capabilities and limitations.";

/** Kept at the front of tool metadata so discovery includes native input. */
export const CUA_INPUT_GUIDANCE =
  'On an attached application window, native input includes await cua.typeText("Hello"), await cua.keyPress("Enter"), await cua.keyPress("A", ["Meta"]), await cua.scroll(300, 0, {x,y}), and await cua.clickDrag({x:20,y:40}, {x:200,y:40}, 200). These use experimental macOS window-directed delivery without requesting activation or moving the system pointer. Text attempts delivery to the target application\'s existing keyboard responder; click the intended field and verify it first. Text supports Unicode (8192 UTF-8 bytes maximum); app frameworks may ignore Unicode events. Key names: Enter, Tab, Escape, Backspace, Delete, ArrowLeft/Right/Up/Down, Home, End, PageUp, PageDown, Space, A-Z and 0-9. Optional modifiers: Shift, Control, Alt, Meta (Command on macOS); letters/digits are physical ANSI shortcut keys, so use typeText for literal text. Scroll deltas are pixels: positive down/right. Drag is one left-button hold/move/release, default 200 ms (50-2000 ms), approximately 60 motion events/second, with custom desktop cursor motion and release cleanup on Stop. No raw held-button or held-key API is exposed. Receipts say background-text/key/scroll/drag, outcome unknown, windowDelivery unverified; a receipt is not proof of application acceptance. Take a fresh snapshot to assess the result; never retry or choose another method after uncertain dispatch. Several awaited calls may share one script. For an explicitly planned sequence on a stable interface (such as piano keys), use await cua.wait(150) between actions; delays are 0-10000 ms each, cancel on Stop, and share the script\'s existing time budget and 64 host-call limit (waits count too). Delays start after the preceding action completes; timing is best effort, not an audio clock. Execute sequentially, never Promise.all for input. Distinct preplanned actions may proceed without a screenshot between them when they do not depend on previous visual results; this does not authorize retrying an uncertain action. If layout, focus or coordinates may change, observe before choosing the next action. An error must stop the sequence; do not catch it to continue posting input.';
