import { spawnSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { repositoryRoot, resolveCantripVersion } from "./version.mjs";

export function renderAndroidVersionProperties(version) {
  return `# Generated by pnpm cap:sync. Do not edit.\nCANTRIP_VERSION_NAME=${version.version}\nCANTRIP_VERSION_CODE=${version.patch}\n`;
}

export function renderIosVersionConfiguration(version) {
  return `// Generated by pnpm cap:sync. Do not edit.\nCANTRIP_VERSION = ${version.version}\nCANTRIP_BUILD_NUMBER = ${version.patch}\n`;
}

export async function writeCapacitorVersionFiles({
  root = repositoryRoot,
  version = resolveCantripVersion({ root }),
} = {}) {
  const androidPath = path.join(
    root,
    "cantrip_app",
    "android",
    "cantrip-version.properties",
  );
  const iosPath = path.join(
    root,
    "cantrip_app",
    "ios",
    "App",
    "cantrip-version.generated.xcconfig",
  );
  await Promise.all([
    mkdir(path.dirname(androidPath), { recursive: true }),
    mkdir(path.dirname(iosPath), { recursive: true }),
  ]);
  await Promise.all([
    writeFile(androidPath, renderAndroidVersionProperties(version), "utf8"),
    writeFile(iosPath, renderIosVersionConfiguration(version), "utf8"),
  ]);
  return { androidPath, iosPath, version };
}

function run(command, arguments_, cwd) {
  const result = spawnSync(command, arguments_, {
    cwd,
    env: process.env,
    stdio: "inherit",
  });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}

const isMain =
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const appRoot = path.join(repositoryRoot, "cantrip_app");
  const pnpm = process.platform === "win32" ? "pnpm.cmd" : "pnpm";
  run(pnpm, ["build"], appRoot);
  run(pnpm, ["exec", "cap", "sync", ...process.argv.slice(2)], appRoot);
  const { version } = await writeCapacitorVersionFiles();
  console.log(`Stamped Capacitor projects with Cantrip ${version.version}`);
}
