import { spawnSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

export const repositoryRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);

function readVersionConfig(root) {
  return JSON.parse(readFileSync(path.join(root, "version.json"), "utf8"));
}

function readGitCommitCount(root) {
  const result = spawnSync("git", ["rev-list", "--count", "HEAD"], {
    cwd: root,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(
      `Could not determine the Cantrip version from Git: ${result.stderr.trim() || "git rev-list failed"}`,
    );
  }
  return result.stdout.trim();
}

function nonNegativeInteger(value, name) {
  if (!Number.isSafeInteger(value) || value < 0) {
    throw new Error(`${name} must be a non-negative safe integer.`);
  }
  return value;
}

function optionalSyntheticValue(environment, name) {
  const value = environment[name]?.trim();
  return value || null;
}

function resolveSyntheticIdentity(environment) {
  const rawSynthetic = environment.CANTRIP_SYNTHETIC_BUILD?.trim();
  if (rawSynthetic && rawSynthetic !== "1") {
    throw new Error("CANTRIP_SYNTHETIC_BUILD must be 1 when enabled.");
  }
  if (!rawSynthetic) {
    return {
      synthetic: false,
      commitSha: null,
      builtAt: null,
      buildId: null,
      overlayDigest: null,
    };
  }

  const commitSha = optionalSyntheticValue(
    environment,
    "CANTRIP_SYNTHETIC_COMMIT_SHA",
  );
  if (!commitSha || !/^[a-f0-9]{40,64}$/u.test(commitSha)) {
    throw new Error(
      "CANTRIP_SYNTHETIC_COMMIT_SHA must be a full lowercase hexadecimal Git commit SHA.",
    );
  }
  const builtAt = optionalSyntheticValue(
    environment,
    "CANTRIP_SYNTHETIC_BUILT_AT",
  );
  if (!builtAt || !Number.isFinite(Date.parse(builtAt))) {
    throw new Error(
      "CANTRIP_SYNTHETIC_BUILT_AT must be a valid ISO-8601 timestamp.",
    );
  }
  const buildId = optionalSyntheticValue(
    environment,
    "CANTRIP_SYNTHETIC_BUILD_ID",
  );
  if (!buildId || !/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$/u.test(buildId)) {
    throw new Error(
      "CANTRIP_SYNTHETIC_BUILD_ID must be a safe non-empty identifier.",
    );
  }
  const overlayDigest = optionalSyntheticValue(
    environment,
    "CANTRIP_SYNTHETIC_OVERLAY_DIGEST",
  );
  if (!overlayDigest || !/^[a-f0-9]{64}$/u.test(overlayDigest)) {
    throw new Error(
      "CANTRIP_SYNTHETIC_OVERLAY_DIGEST must be a lowercase SHA-256 digest.",
    );
  }

  return {
    synthetic: true,
    commitSha,
    builtAt: new Date(builtAt).toISOString(),
    buildId,
    overlayDigest,
  };
}

export function resolveCantripVersion({
  root = repositoryRoot,
  environment = process.env,
  loadVersionConfig = readVersionConfig,
  loadGitCommitCount = readGitCommitCount,
} = {}) {
  const config = loadVersionConfig(root);
  if (!config || typeof config !== "object" || Array.isArray(config)) {
    throw new Error("version.json must contain a JSON object.");
  }
  const keys = Object.keys(config).sort();
  if (keys.join(",") !== "major,minor") {
    throw new Error("version.json must contain only major and minor fields.");
  }

  const major = nonNegativeInteger(config.major, "version.json major");
  const minor = nonNegativeInteger(config.minor, "version.json minor");
  const patchOverride = environment.CANTRIP_VERSION_PATCH?.trim();
  const rawPatch = patchOverride || loadGitCommitCount(root);
  if (!/^\d+$/u.test(rawPatch)) {
    throw new Error(
      `${patchOverride ? "CANTRIP_VERSION_PATCH" : "Git commit count"} must be a non-negative integer.`,
    );
  }
  const patch = nonNegativeInteger(
    Number(rawPatch),
    patchOverride ? "CANTRIP_VERSION_PATCH" : "Git commit count",
  );

  const syntheticIdentity = resolveSyntheticIdentity(environment);

  return Object.freeze({
    major,
    minor,
    patch,
    version: `${major}.${minor}.${patch}${syntheticIdentity.synthetic ? "-x" : ""}`,
    ...syntheticIdentity,
  });
}

export function renderVersionModule(version) {
  return `// Generated by scripts/version.mjs. Do not edit.\nexport const CANTRIP_VERSION = ${JSON.stringify(version.version)};\nexport const cantripVersion = Object.freeze(${JSON.stringify(version, null, 2)});\nexport default cantripVersion;\n`;
}

export async function buildVersionPackage({ root = repositoryRoot } = {}) {
  const version = resolveCantripVersion({ root });
  const outputDirectory = path.join(root, "packages", "version", "dist");
  await mkdir(outputDirectory, { recursive: true });
  await Promise.all([
    writeFile(
      path.join(outputDirectory, "index.js"),
      renderVersionModule(version),
      "utf8",
    ),
    writeFile(
      path.join(outputDirectory, "version.json"),
      `${JSON.stringify(version, null, 2)}\n`,
      "utf8",
    ),
  ]);
  return version;
}

const isMain =
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  if (process.argv[2] === "build-package") {
    const version = await buildVersionPackage();
    console.log(`Built @cantrip/version ${version.version}`);
  } else if (process.argv.length === 2) {
    console.log(resolveCantripVersion().version);
  } else {
    console.error("Usage: node scripts/version.mjs [build-package]");
    process.exitCode = 1;
  }
}
